// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMaUuiuqxk817VdK09sN48ah9GbERwVmo',
    appId: '1:56036794339:web:a66cc42096c4575ff44ad6',
    messagingSenderId: '56036794339',
    projectId: 'expensetracker-44881',
    authDomain: 'expensetracker-44881.firebaseapp.com',
    storageBucket: 'expensetracker-44881.firebasestorage.app',
    measurementId: 'G-1YPWC34JK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO3lemJQwFFRDBwS9bOjMaEk0DXWmz3Vk',
    appId: '1:56036794339:android:2aff254395644546f44ad6',
    messagingSenderId: '56036794339',
    projectId: 'expensetracker-44881',
    storageBucket: 'expensetracker-44881.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfXbRoTi4SrlRYxU15bwO0J8l54dlsatQ',
    appId: '1:56036794339:ios:139bcdd0832e23cff44ad6',
    messagingSenderId: '56036794339',
    projectId: 'expensetracker-44881',
    storageBucket: 'expensetracker-44881.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfXbRoTi4SrlRYxU15bwO0J8l54dlsatQ',
    appId: '1:56036794339:ios:139bcdd0832e23cff44ad6',
    messagingSenderId: '56036794339',
    projectId: 'expensetracker-44881',
    storageBucket: 'expensetracker-44881.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMaUuiuqxk817VdK09sN48ah9GbERwVmo',
    appId: '1:56036794339:web:9016fbed881e914cf44ad6',
    messagingSenderId: '56036794339',
    projectId: 'expensetracker-44881',
    authDomain: 'expensetracker-44881.firebaseapp.com',
    storageBucket: 'expensetracker-44881.firebasestorage.app',
    measurementId: 'G-J38V3K1FQQ',
  );
}
